version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'benhigham'
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      github-actions:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'benhigham'
    labels:
      - 'dependencies'
      - 'npm'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      development-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      production-dependencies:
        dependency-type: 'production'
        update-types:
          - 'patch'
    versioning-strategy: increase

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'benhigham'
    labels:
      - 'dependencies'
      - 'docker'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'terraform'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'benhigham'
    labels:
      - 'dependencies'
      - 'terraform'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'benhigham'
    labels:
      - 'dependencies'
      - 'devcontainers'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'benhigham'
    labels:
      - 'dependencies'
      - 'git-submodules'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'benhigham'
    labels:
      - 'dependencies'
      - 'go'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      go-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
