title: "[Idea] "
labels: enhancement

body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature or enhancement you have in mind
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem It Solves
      description: Explain the problem this feature would address
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas on how to implement this feature, share them here
    validations:
      required: false

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you considered
    validations:
      required: false
