title: "[Question] "
labels: question

body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Provide a clear and concise description of your question
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background information that may help others understand your question
    validations:
      required: false

  - type: textarea
    id: investigation
    attributes:
      label: Investigation Steps
      description: Describe any steps you've taken to find a solution or any resources you've consulted
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment (if applicable)
      description: Provide details about your environment (e.g., OS, version, etc.) if relevant to your question
    validations:
      required: false
