name: 💡 Feature Request
description: Request a new feature or enhancement
title: "feat: "
labels: ["enhancement"]
assignees: ["benhigham"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature 🌟
        Please make sure there aren't any existing issues for this feature request 🙏

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a clear and concise summary of the feature
      placeholder: e.g., "Add dark mode support"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a detailed description of the feature or enhancement you would like
      placeholder: Explain how the feature would work, what problem it solves, and any specific requirements
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be used, and who would use it?
      placeholder: Describe the scenarios where this feature would be valuable and which users would benefit
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my work)
        - High (significantly improves my experience)
        - Medium (would be a nice addition)
        - Low (just an idea)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What specific outcomes would indicate this feature is successfully implemented?
      placeholder: |
        Example:
        - Users can toggle between light and dark mode
        - Mode preference is saved between sessions
        - All UI elements properly adapt to the selected mode
    validations:
      required: false

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How much effort do you think implementing this feature would require?
      options:
        - Small (few hours)
        - Medium (few days)
        - Large (1-2 weeks)
        - X-Large (more than 2 weeks)
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Provide any additional context, proposed solutions, links, screenshots, etc.
    validations:
      required: false
