name: CI

on:
  workflow_call:
    inputs:
      node-version:
        description: |
          The version of Node.js to use (supports the Semantic Versioning Specification, e.g. 18.x, ^20.10.0, >=21)
          If not specified, the version will be read from package.json.
        type: string
        required: false
      pnpm-version:
        description: |
          The version of pnpm to use (supports the Semantic Versioning Specification, e.g. 8, 10.7.0, latest)
          If not specified, the version will be read from package.json.
        type: string
        required: false
      run-lint:
        description: Whether to run the lint step
        type: boolean
        default: true
        required: false
      lint-command:
        description: The command to run for linting
        type: string
        default: pnpm run lint
        required: false
      run-typecheck:
        description: Whether to run the type checking step
        type: boolean
        default: true
        required: false
      typecheck-command:
        description: The command to run for type checking
        type: string
        default: pnpm run typecheck
        required: false
      run-test:
        description: Whether to run tests
        type: boolean
        default: true
        required: false
      test-command:
        description: The command to run tests
        type: string
        default: pnpm run test
        required: false
      run-build:
        description: Whether to run the build step
        type: boolean
        default: false
        required: false
      build-command:
        description: The command to run for building
        type: string
        default: pnpm run build
        required: false
      upload-coverage:
        description: Whether to upload coverage reports as artifacts
        type: boolean
        default: false
        required: false
      coverage-path:
        description: Path to coverage reports
        type: string
        default: coverage
        required: false

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    if: inputs.run-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: package.json
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        timeout-minutes: 5

      - name: Run linting
        run: ${{ inputs.lint-command }}

  typecheck:
    name: Type check
    if: inputs.run-typecheck
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: package.json
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        timeout-minutes: 5

      - name: Run type checking
        run: ${{ inputs.typecheck-command }}

  test:
    name: Test
    if: inputs.run-test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: package.json
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        timeout-minutes: 5

      - name: Run tests
        run: ${{ inputs.test-command }}

      - name: Upload coverage reports
        if: inputs.upload-coverage && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ${{ inputs.coverage-path }}
          retention-days: 30

  build:
    name: Build
    if: inputs.run-build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: package.json
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        timeout-minutes: 5

      - name: Build
        run: ${{ inputs.build-command }}
