# Automated release workflow using Changesets for version management and npm publishing.
# Supports optional build steps, NPM provenance, and automatic changelog generation.
# Creates version bump PRs and publishes packages when merged.
name: Release changesets

on:
  workflow_call:
    inputs:
      node-version:
        description: |
          The version of Node.js to use (supports the Semantic Versioning Specification, e.g. 18.x, ^20.10.0, >=21)
          If not specified, the version will be read from package.json.
        type: string
        required: false
      pnpm-version:
        description: |
          The version of pnpm to use (supports the Semantic Versioning Specification, e.g. 8, 10.7.0, latest)
          If not specified, the version will be read from package.json.
        type: string
        required: false
      needs-build:
        description: Whether to run the build step before publishing
        type: boolean
        default: false
        required: false
      version-command:
        description: The command to update version, edit CHANGELOG, read and delete changesets
        type: string
        default: pnpm run version
        required: false
      publish-command:
        description: The command to publish packages
        type: string
        default: pnpm run release
        required: false
      commit-message:
        description: Commit message for the version bump
        type: string
        default: "chore(release): bump package versions"
        required: false
      pr-title:
        description: Title of the pull request
        type: string
        default: "chore(release): create new release"
        required: false
    secrets:
      NPM_TOKEN:
        required: true

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  release:
    name: Create release
    permissions:
      attestations: write # to create attestations (changesets/action)
      contents: write # to create the release (changesets/action)
      id-token: write # for npm provenance verification (changesets/action)
      issues: write # to post issue comments (changesets/action)
      pull-requests: write # to create the pull request (changesets/action)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      cache-hit: ${{ steps.setup-node-pnpm.outputs.cache-hit }}
    steps:
      - name: Setup Node.js with pnpm
        id: setup-node-pnpm
        uses: benhigham/.github/.github/actions/setup-node-pnpm@main
        with:
          node-version: ${{ inputs.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}

      - name: Build packages
        if: inputs.needs-build
        run: pnpm run build
        timeout-minutes: 5

      - name: Create and publish a new release
        uses: changesets/action@v1
        with:
          version: ${{ inputs.version-command }}
          publish: ${{ inputs.publish-command }}
          commit: ${{ inputs.commit-message }}
          title: ${{ inputs.pr-title }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
