# Automatically marks and closes stale issues and PRs after configured periods of inactivity.
# Highly configurable with exemptions, custom messages, and separate timeouts for issues vs PRs.
name: Stale Issues and PRs

on:
  workflow_call:
    inputs:
      days-before-stale:
        description: Days of inactivity before marking as stale
        type: number
        default: 60
        required: false
      days-before-close:
        description: Days before closing stale issues/PRs
        type: number
        default: 7
        required: false
      exempt-issue-labels:
        description: Comma-separated list of labels that exempt issues from being marked stale
        type: string
        default: "priority: critical,priority: high,status: blocked"
        required: false
      exempt-pr-labels:
        description: Comma-separated list of labels that exempt PRs from being marked stale
        type: string
        default: "priority: critical,priority: high,status: blocked"
        required: false
      stale-issue-label:
        description: Label to use when marking issues as stale
        type: string
        default: stale
        required: false
      stale-pr-label:
        description: Label to use when marking PRs as stale
        type: string
        default: stale
        required: false
      stale-issue-message:
        description: Message to comment when marking an issue as stale
        type: string
        default: |
          This issue has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs. Thank you
          for your contributions.
        required: false
      stale-pr-message:
        description: Message to comment when marking a PR as stale
        type: string
        default: |
          This pull request has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs. Thank you
          for your contributions.
        required: false
      close-issue-message:
        description: Message to comment when closing a stale issue
        type: string
        default: Closing this issue due to inactivity.
        required: false
      close-pr-message:
        description: Message to comment when closing a stale PR
        type: string
        default: Closing this pull request due to inactivity.
        required: false

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: stale-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stale:
    name: Mark and close stale issues/PRs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Mark and close stale issues and PRs
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: ${{ inputs.days-before-stale }}
          days-before-close: ${{ inputs.days-before-close }}
          exempt-issue-labels: ${{ inputs.exempt-issue-labels }}
          exempt-pr-labels: ${{ inputs.exempt-pr-labels }}
          stale-issue-label: ${{ inputs.stale-issue-label }}
          stale-pr-label: ${{ inputs.stale-pr-label }}
          stale-issue-message: ${{ inputs.stale-issue-message }}
          stale-pr-message: ${{ inputs.stale-pr-message }}
          close-issue-message: ${{ inputs.close-issue-message }}
          close-pr-message: ${{ inputs.close-pr-message }}
          operations-per-run: 100
