name: Sync Labels

on:
  push:
    branches: [main]
    paths:
      - ".github/labels.yml"
  workflow_dispatch:

permissions:
  issues: write
  contents: read

concurrency:
  group: sync-labels-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    name: Sync Repository Labels
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Sync labels
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
          repository: ${{ github.repository }}
          prune: true
